# Generated by Django 3.0.8 on 2020-08-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carengine',
            name='dsg_price',
        ),
    ]
