# Generated by Django 3.0.8 on 2020-09-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='brand_image',
        ),
    ]
